### ISSUE TITLE
injector tool seems to always fail when run from windows

### ISSUE THREAD

**Issue by ynbchery** [pivotal-cf/winfs-injector#3]
I have tried running the winfs-injector tool on three different windows OS:
Windows 7
Windows Server 2012r2
Windows Server 2016

All of them failed with the same error message. Seems like the issue is how the tar command is called with win os:

PS C:\Users\user\Downloads> .\winfs-injector-windows.exe --input-tile .\pas-windows-2.1.6-build.1.pivotal --output-
tile pas-windows-2.1.6-INJECTED.pivotal
Downloading 14 layers...
Layer diffID: 4bfe49d7, sha256: 5847a47b begin
Layer diffID: fba90ef0, sha256: 96b0893d begin
Layer diffID: c7df042b, sha256: af675e50 begin
Layer diffID: b754bd68, sha256: 7419325b begin
Layer diffID: ab415e7c, sha256: cc8ef44f begin
Layer diffID: 8e7b56a1, sha256: 34a3bcdf begin
Layer diffID: f39b2d9e, sha256: 74453d58 begin
Layer diffID: 1557cec7, sha256: 33805614 begin
Layer diffID: 2585965c, sha256: 46bf1b32 begin
Layer diffID: 44be9818, sha256: c9bb60cf begin
Layer diffID: 4fdd5d4b, sha256: cae43687 begin
Layer diffID: b5ed1b85, sha256: f0db3ab6 begin
Layer diffID: 60f6b122, sha256: 90ceec91 begin
Layer diffID: eda1a50c, sha256: 00486217 begin
Layer diffID: fba90ef0, sha256: 96b0893d end
Layer diffID: ab415e7c, sha256: cc8ef44f end
Layer diffID: 44be9818, sha256: c9bb60cf end
Layer diffID: 4fdd5d4b, sha256: cae43687 end
Layer diffID: b754bd68, sha256: 7419325b end
Layer diffID: 60f6b122, sha256: 90ceec91 end
Layer diffID: 2585965c, sha256: 46bf1b32 end
Layer diffID: f39b2d9e, sha256: 74453d58 end
Layer diffID: b5ed1b85, sha256: f0db3ab6 end
Layer diffID: 8e7b56a1, sha256: 34a3bcdf end
Layer diffID: eda1a50c, sha256: 00486217 end
Layer diffID: 1557cec7, sha256: 33805614 end
Layer diffID: c7df042b, sha256: af675e50 end
Layer diffID: 4bfe49d7, sha256: 5847a47b end

All layers downloaded.
Writing C:\Users\user\AppData\Local\Temp\2\586982183\extracted-tile\embed\windows2016fs-release\blobs\windows2016fs\
windows2016fs-0.0.55.tgz...
Done.
Building a release from directory 'C:\Users\user\AppData\Local\Temp\2\586982183\extracted-tile\embed\windows2016fs-r
elease': Compressing staging directory: Shelling out to tar: Running command: 'powershell tar czf C:\Users\user\.bo
sh\tmp\bosh-platform-disk-TarballCompressor-CompressSpecificFilesInDir248341323 -C C:\Users\user\.bosh\tmp\bosh-res
ource-archive930953372 .', stdout: '', stderr: 'tar (child): Cannot connect to C: resolve failed
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
': exit status 1

**Comment by sunjayBhatia** [comment]
@ynbchery looks like you need `BSD tar` and you have `GNU tar`

**Comment by ynbchery** [comment]
I just want to confirm the same command works perfectly fine on Ubuntu

**Comment by sunjayBhatia** [comment]
the `README`  has a link to `BSD tar` for Windows

**Comment by ynbchery** [comment]
I'm using whatever TAR that was bundled with the latest release on pivnet.

I'm fine changing it manually but shouldn't the right binaries be included in the package?

**Comment by sunjayBhatia** [comment]
Are you sure the right `tar.exe` is on your path?

What is the output of `tar --version`

**Comment by sunjayBhatia** [comment]
@awmartin @natalieparellano

**Comment by ynbchery** [comment]
PS C:\Users\user> tar --version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11

**Comment by ynbchery** [comment]
I ran a search & it looks like I had 2 versions of tar installed. While it seems to default to the BSD while running through the command line, the winfs injector was defaulting to the version included as part of the git for windows installed.

I replaced the binary with the one provided by this tool & re-ran the command. I'll post the result shortly once its done.

**Comment by sunjayBhatia** [comment]
hmmm maybe the search path order is different between Powershell  and golang, though that seems a bit surprising

**Comment by ynbchery** [comment]
I think we are good now. Thanks for the quick response, unless you think there are additional actions feel free to close this case:

All layers downloaded.
Writing C:\Users\user\AppData\Local\Temp\2\222481207\extracted-tile\embed\windows2016fs-release\blobs\windows2016fs\
windows2016fs-0.0.55.tgz...
Done.
Adding job 'windows2016fs/3f0192df4db7e36a93f4c0694ddb15150fd75061'...
Added job 'windows2016fs/3f0192df4db7e36a93f4c0694ddb15150fd75061'
Adding package 'windows2016fs/0e6133da5126d8592dff667d57236adb71c38598'...
Added package 'windows2016fs/0e6133da5126d8592dff667d57236adb71c38598'
Adding license 'license/1cd1860c9522cc46ab61d561ead70a94ac790295'...
Added license 'license/1cd1860c9522cc46ab61d561ead70a94ac790295'

Added dev release 'windows2016fs/1.3.0'
[release.ArchiveWriter] 2018/06/15 13:10:16 INFO - Writing release tarball into 'C:\Users\user\.bosh\tmp\bosh-relea
se757639698'

←[1mName←[0m         windows2016fs
←[1mVersion←[0m      1.3.0
←[1mCommit Hash←[0m  bbb7a05
←[1mArchive←[0m      C:\Users\user\AppData\Local\Temp\2\222481207\extracted-tile\releases\windows2016fs-1.3.0.tgz

←[1mJob←[0m                                                     ←[1mDigest←[0m                                    ←[1mPa
ckages←[0m
windows2016fs/3f0192df4db7e36a93f4c0694ddb15150fd75061  960556320d90cd2097215cac9993468caab96b32  windows2016fs

1 jobs

←[1mPackage←[0m                                                 ←[1mDigest←[0m                                    ←[1mDe
pendencies←[0m
windows2016fs/0e6133da5126d8592dff667d57236adb71c38598  a8bed2c10e676f2258de807e09bb8b5eea78fa85  -

1 packages

**Comment by sunjayBhatia** [comment]
I'll leave closing this up to @pivotal-cf/pcf-release-engineering
