### ISSUE TITLE
`winfs-injector` doesn't work on windows due to permission errors

### ISSUE THREAD

**Issue by rizwanreza** [pivotal-cf/winfs-injector#5]
We recently [made a change to kiln](https://github.com/pivotal-cf/kiln/commit/3e8211a50c9199edfe6a70118af401d73a21c774) that makes the embed directory isn't a git repository. We rely on that directory [to be a git repository on windows for fixing file permissions before operating on it](https://github.com/pivotal-cf/winfs-injector/blob/4f5038a2141d9e2a229e7b9190db03ebfb45ce35/winfsinjector/application.go#L97-L111).

We should either revert the change in kiln or find a Windows compatible mechanism to fix this issue.

Here is [the original reported issue on Slack](https://pivotal.slack.com/archives/C0555LE4W/p1545923115014200):

> With winfs-injector-0.11 and the latest pas-windows-2.4.1-build1.pivotal tile available in pivnet,
getting this error while creating the tile:
```winfs-injector-windows.exe --input-tile pas-windows-2.4.1-build.1.pivotal --output-tile pas-windows-PASW2.4.1-build.1.pivotal "unable to fix file permissions for windows:fatal:not in a git directory, exit status 128"```
, I tried the winfs-injector-0.11 with previous build 2.4.0, no issue

**The workaround currently is to use a Linux machine to inject the release into the tile.**

**Comment by kartiklunkad26** [comment]
This bug is now resolved. Here's the KB article regarding this: https://community.pivotal.io/s/article/winfs-injector-windows-fails-when-building-pasw-tile

**Comment by genevieve** [comment]
@rizwanreza I think you can close this issue!
